### ISSUE TITLE
HttpServletResponse needed in middlewares

### ISSUE THREAD

**Issue by olucurious** [SeunAdelekan/Kanary#2]
It will be awesome, in fact it is essential to be able to write a response and send it in middlewares without handing out to any router.

https://github.com/SeunAdelekan/Kanary/blob/master/src/main/com/iyanuadelekan/kanary/app/KanaryApp.kt#L32

**Comment by SeunAdelekan** [comment]
@olucurious that's a great suggestion. Would be great if you could work on that and send in a pull request.
