### ISSUE TITLE
Confusing routes definition

### ISSUE THREAD

**Issue by olucurious** [SeunAdelekan/Kanary#3]
The Kanary router system forces one to append a '/' at the end of every router declaration even when the resulting url will end without '/'

For example:
   ` userRouter.get("details/", userController::retrieveUser)`
will result in '/user/details' and it can be confusing when reading or writing code, there should be a way to do this instead:
   ` userRouter.get("details", userController::retrieveUser)`
That's clearer and easier to wrap one's head around.

**Comment by SeunAdelekan** [comment]
@olucurious Thanks again for this suggestion. Would you like to work on this issue?

**Comment by SeunAdelekan** [comment]
@alkern your pull request has been merged. Thanks for your contribution!
