### ISSUE TITLE
how can fix the cors

### ISSUE THREAD

**Issue by luckyxiaomo** [SeunAdelekan/Kanary#37]
i am sorry for my poor english

how can fix the cors?

**Comment by SeunAdelekan** [comment]
Hi @luckyxiaomo 
Issues pertaining to CORS can be resolved by creating a corresponding OPTIONS route that responds with an HTTP 200 for routes experiencing CORS related issues. Kindly check [here](https://github.com/olucurious/Kanary-Mini-Twitter-Clone/blob/master/src/curious/cwitter/app.kt) to view an example.

**Comment by luckyxiaomo** [comment]
thanks，but i selected the ktor ，because of its well-documented
